import json
import os
import struct
import sys
import asyncio
import threading
import queue
import time
from collections import deque
from dotenv import load_dotenv

try:
    import numpy as np
except ImportError:
    np = None

try:
    from google import genai
    from google.genai import types
    from google.genai.types import (
        Content,
        FunctionDeclaration,
        LiveConnectConfig,
        Part,
        PrebuiltVoiceConfig,
        SpeechConfig,
        Tool,
        VoiceConfig,
    )
    from google.genai.types import Schema
    from google.genai.types import Type as SchemaType
    print("[Info] google-genai package loaded successfully")
except ImportError:
    genai = None
    types = None
    Content = Part = LiveConnectConfig = SpeechConfig = VoiceConfig = None
    PrebuiltVoiceConfig = Tool = FunctionDeclaration = Schema = SchemaType = None
    print("[Warning] google-genai package not found. Install with: pip install google-genai")

try:
    import pyaudio
    print("[Info] pyaudio loaded successfully")
except ImportError:
    pyaudio = None
    print("[Warning] pyaudio not found. Install with: pip install pyaudio")

try:
    from websockets.exceptions import ConnectionClosedError as WsConnectionClosedError
except ImportError:
    WsConnectionClosedError = None

try:
    from .agent import Agent
except ImportError:
    from agent import Agent

# Load env from repo root (two levels up from query_pipeline)
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DOTENV_PATH = os.path.join(_REPO_ROOT, ".env")
load_dotenv(dotenv_path=DOTENV_PATH, override=True)

def _load_generate_nao_code():
    try:
        from memobot.tools import generate_nao_code
        return generate_nao_code
    except ImportError:
        pass
    try:
        from tools import generate_nao_code
        return generate_nao_code
    except ImportError:
        pass
    # Fallback: load from memobot/tools relative to repo root
    _tools_path = os.path.join(_REPO_ROOT, "memobot", "tools")
    if os.path.isdir(_tools_path) and _tools_path not in sys.path:
        sys.path.insert(0, os.path.join(_REPO_ROOT, "memobot"))
        try:
            from tools import generate_nao_code
            return generate_nao_code
        except ImportError:
            pass
    return None

generate_nao_code = _load_generate_nao_code()

MemobotService = None
DEFAULT_MEMOBOT_GROUP_ID = os.getenv("MEMOBOT_GROUP_ID", "tenant_001")

# Global: last code generated by writeCode (NAO robot). Updated when writeCode is called with coding_prompt.
last_code = None
# Set True when writeCode has finished writing code; executeCode checks this before sending to robot.
code_status = False
# Socket to send code to robot client (set by robot server e.g. mac_master when command client connects).
code_command_socket = None


def set_code_command_socket(sock):
    """Call from robot server when a command client connects; pass None when client disconnects."""
    global code_command_socket
    code_command_socket = sock

try:
    from Memobot import MemobotService
    print("[Info] Memobot package loaded successfully")
except ImportError:
    pass

# Audio config
FORMAT = pyaudio.paInt16 if pyaudio else None
CHANNELS = 1
SEND_SAMPLE_RATE = 16000      # Gemini expects 16kHz input
RECEIVE_SAMPLE_RATE = 24000   # Gemini outputs 24kHz audio
CHUNK_SIZE = 512              # Small chunks for lower latency

# Echo cancellation settings
PLAYBACK_GRACE_PERIOD = 0.5   # Increased to 500ms for better echo prevention
MIC_QUEUE_MAXSIZE = 3         # Reduced to prevent audio backlog

MODEL = "gemini-2.5-flash-native-audio-preview-12-2025"
# Model for writeCode: generateContent (text/code) API
CODE_GENERATION_MODEL = "gemini-3-flash-preview"
VOICE_NAME = "Aoede"

NAO_CODE_SYSTEM_PROMPT = (
    "You are a NAO robot (Aldebaran/SoftBank) code generator. "
    "Output ONLY raw Python code compatible with NAOqi (Python 2.7 style). "
    "Use ALProxy for motion, speech, etc. No markdown, no explanation—just runnable code."
)

BASE_INSTRUCTIONS = (
    "You are Mnemo, a NAO V4 robot (Aldebaran/SoftBank). You have a voice and a body; you can move, gesture, and run code on the robot.\n\n"
    "LANGUAGE: Speak in English, Chinese (中文), or Indonesian (Bahasa Indonesia) as appropriate—match the user's language or use English by default. Keep replies short.\n\n"
    "TOOLS — use them when relevant:\n"
    "• retrieveMemory: Call when the user asks about the past, preferences, people, or anything that might be in memory. Do not answer from memory without calling it. Do not guess. Do NOT call retrieveMemory for identity questions like 'who am I', 'what is my name', 'what's my name'—answer from the current speaker context (you are told who is speaking).\n"
    "• searchRobotActions: Call when the user wants to know what actions you can do (e.g. movements, gestures, speech) or when you need to look up available robot actions by keyword or category.\n"
    "• writeCode: Call when the user wants you to do something programmable on the robot (e.g. dance, wave, walk, say something specific, perform a sequence). Provide a clear coding_prompt describing the behavior. Code is generated for NAO (Python/naoqi).\n"
    "• executeCode: Call only after writeCode has been used. When the user says to run, execute, or perform the code (e.g. 'run it', 'execute', 'do it'), call executeCode to send the last generated code to the robot. Do not call executeCode before writeCode.\n"
    "• saveCode: Call when the user explicitly asks to save the code to a file; provide code and filename.\n"
    "• updateMyName: Call when the user says their name (e.g. 'My name is Jason', 'Call me Sarah'). Updates the current speaker's name in the database. Use the name they give.\n\n"
    "RULES: Do not make up facts. Be concise. If unsure, say so."
)


def _get_retrieve_memory_tool():
    """Return a Tool for retrieveMemory (typed for Live API)."""
    if Tool is None or FunctionDeclaration is None or Schema is None or SchemaType is None:
        return None
    return Tool(
        function_declarations=[
            FunctionDeclaration(
                name="retrieveMemory",
                description="Retrieve past memories based on a natural language query. Do not use for identity questions (e.g. who am I, what is my name)—use the current speaker context instead.",
                parameters=Schema(
                    type=SchemaType.OBJECT,
                    properties={
                        "queryText": Schema(
                            type=SchemaType.STRING,
                            description="The natural language query to search for memories.",
                        ),
                    },
                    required=["queryText"],
                ),
            )
        ]
    )


def _get_extra_tools():
    """Return a Tool with searchRobotActions, writeCode, executeCode, saveCode (typed for Live API)."""
    if Tool is None or FunctionDeclaration is None or Schema is None or SchemaType is None:
        return None
    return Tool(
        function_declarations=[
            FunctionDeclaration(
                name="searchRobotActions",
                description="Search for available robot actions (e.g. move, grasp, speak) by keyword or category.",
                parameters=Schema(
                    type=SchemaType.OBJECT,
                    properties={
                        "query": Schema(
                            type=SchemaType.STRING,
                            description="Search query for robot actions.",
                        ),
                        "category": Schema(
                            type=SchemaType.STRING,
                            description="Optional category to filter actions (e.g. movement, manipulation, speech).",
                        ),
                    },
                    required=["query"],
                ),
            ),
            FunctionDeclaration(
                name="writeCode",
                description="Write or generate code for the NAO V4 robot (Python/naoqi). Use coding_prompt for the user's request. Returns the generated code.",
                parameters=Schema(
                    type=SchemaType.OBJECT,
                    properties={
                        "coding_prompt": Schema(
                            type=SchemaType.STRING,
                            description="Natural language description of what the robot code should do.",
                        ),
                        "prompt": Schema(
                            type=SchemaType.STRING,
                            description="Alternative to coding_prompt: description of what the code should do.",
                        ),
                        "language": Schema(
                            type=SchemaType.STRING,
                            description="Programming language (e.g. python). Default python for NAO.",
                        ),
                    },
                    required=[],
                ),
            ),
            FunctionDeclaration(
                name="executeCode",
                description="Send the last generated code (last_code) to the robot client via TCP. Fails if code_status is False (user must call writeCode first). When code_status is True, sends last_code to the connected robot.",
                parameters=Schema(
                    type=SchemaType.OBJECT,
                    properties={
                        "code": Schema(
                            type=SchemaType.STRING,
                            description="Optional; for robot flow the code in last_code is sent when code_status is True.",
                        ),
                        "language": Schema(
                            type=SchemaType.STRING,
                            description="Programming language (e.g. python).",
                        ),
                    },
                    required=[],
                ),
            ),
            FunctionDeclaration(
                name="saveCode",
                description="Save code to a file or named snippet in the project.",
                parameters=Schema(
                    type=SchemaType.OBJECT,
                    properties={
                        "code": Schema(
                            type=SchemaType.STRING,
                            description="The code to save.",
                        ),
                        "filename": Schema(
                            type=SchemaType.STRING,
                            description="Filename or path to save the code to.",
                        ),
                    },
                    required=["code", "filename"],
                ),
            ),
            FunctionDeclaration(
                name="updateMyName",
                description="Update the current speaker's name in the database. Call when the user says their name (e.g. 'My name is Jason', 'Call me Sarah').",
                parameters=Schema(
                    type=SchemaType.OBJECT,
                    properties={
                        "name": Schema(
                            type=SchemaType.STRING,
                            description="The name the user wants to be called (e.g. Jason, Sarah).",
                        ),
                    },
                    required=["name"],
                ),
            ),
        ]
    )


class AudioManager:
    def __init__(self):
        self.p = pyaudio.PyAudio() if pyaudio else None
        self.in_stream = None
        self.out_stream = None
        self.play_queue = queue.Queue(maxsize=100)  # Bounded queue to prevent excessive buffering
        self.playback_thread = None
        self.is_running = True
        self.last_playback_time = 0  # Timestamp when last audio finished playing
        self._lock = threading.Lock()

    async def init(self):
        if not self.p:
            return
        
        try:
            mic_info = self.p.get_default_input_device_info()
            # Mic input - optimized for minimal latency
            self.in_stream = self.p.open(
                format=FORMAT,
                channels=CHANNELS,
                rate=SEND_SAMPLE_RATE,
                input=True,
                input_device_index=mic_info["index"],
                frames_per_buffer=CHUNK_SIZE,
                stream_callback=None,  # Use blocking mode for simplicity
            )
            # Speaker output - optimized for minimal latency
            self.out_stream = self.p.open(
                format=FORMAT,
                channels=CHANNELS,
                rate=RECEIVE_SAMPLE_RATE,
                output=True,
                frames_per_buffer=CHUNK_SIZE * 2,  # Slightly larger output buffer
            )
            print("🎤 Mic + 🔈 Speaker initialized")
            print(f"📊 Audio Config: Input={SEND_SAMPLE_RATE}Hz, Output={RECEIVE_SAMPLE_RATE}Hz, Chunk={CHUNK_SIZE}")
            
            # Start dedicated playback thread
            self.playback_thread = threading.Thread(target=self._playback_loop, daemon=True)
            self.playback_thread.start()
            
        except Exception as e:
            print(f"Error initializing audio: {e}")
            raise

    def read_mic(self):
        # Check if we're in grace period after playback
        with self._lock:
            time_since_playback = time.time() - self.last_playback_time
            if time_since_playback < PLAYBACK_GRACE_PERIOD:
                return b'\x00' * (CHUNK_SIZE * 2)  # Return silence during grace period
            
        try:
            if self.in_stream:
                return self.in_stream.read(CHUNK_SIZE, exception_on_overflow=False)
            return b'\x00' * (CHUNK_SIZE * 2)
        except Exception as e:
            print(f"Error reading microphone: {e}")
            return b'\x00' * (CHUNK_SIZE * 2)

    def queue_audio(self, data: bytes):
        if self.is_running:
            self.play_queue.put(data)

    def _playback_loop(self):
        while self.is_running:
            try:
                if self.play_queue.empty():
                    time.sleep(0.001)  # Very short sleep when idle
                    continue
                    
                data = self.play_queue.get(timeout=0.05)
                if self.out_stream:
                    self.out_stream.write(data)
                
                # Update last playback time
                with self._lock:
                    self.last_playback_time = time.time()
                    
                self.play_queue.task_done()
                    
            except queue.Empty:
                continue
            except Exception as e:
                print(f"Error playing audio: {e}")
                time.sleep(0.05)

    def interrupt(self, print_message=False):
        """Handle interruption by clearing queue. Set print_message=True only when user interrupted (not when AI finished)."""
        try:
            while not self.play_queue.empty():
                self.play_queue.get_nowait()
                self.play_queue.task_done()
        except queue.Empty:
            pass
        
        # Reset last playback time to allow immediate mic input
        with self._lock:
            self.last_playback_time = 0
        if print_message:
            print("🔇 Audio playback interrupted")

    def cleanup(self):
        self.is_running = False
        if self.playback_thread:
            self.playback_thread.join(timeout=1.0)
            
        if self.in_stream:
            try:
                self.in_stream.stop_stream()
                self.in_stream.close()
            except: pass
        if self.out_stream:
            try:
                self.out_stream.stop_stream()
                self.out_stream.close()
            except: pass
        if self.p:
            self.p.terminate()
        print("🎤 Mic + 🔈 Speaker cleaned up")


class RealtimeAgent:
    def __init__(self, api_key=None, user_name=None, person_id=None):
        self.api_key = api_key or os.environ.get("GOOGLE_API_KEY")
        self.user_name = user_name
        self.person_id = person_id
        self.client = genai.Client(
            api_key=self.api_key,
            http_options={"api_version": "v1alpha"},
        )
        self.session = None
        self.memobot_service = None
        self.audio_mgr = AudioManager()
        
        # Queue for sending mic audio to gemini - smaller to reduce latency
        self.audio_queue_mic = asyncio.Queue(maxsize=MIC_QUEUE_MAXSIZE)
        
        self._init_memobot_service()
    
    def _init_memobot_service(self):
        if MemobotService is None:
            return
        try:
            self.memobot_service = MemobotService.from_env(group_id=DEFAULT_MEMOBOT_GROUP_ID)
            print("[Info] MemobotService initialized")
        except Exception as e:
            print(f"[Warning] Failed to initialize MemobotService: {e}")

    def _generate_code_via_api_sync(self, coding_prompt: str) -> str:
        """Call Gemini generateContent API to generate NAO robot code. Returns code string or raises."""
        if not genai or not self.client:
            raise RuntimeError("Gemini client not available")
        prompt = f"{NAO_CODE_SYSTEM_PROMPT}\n\nUser request: {coding_prompt}"
        try:
            if types and hasattr(types, "Part") and hasattr(types.Part, "from_text"):
                contents = types.Part.from_text(text=prompt)
            elif types and hasattr(types, "Content") and hasattr(types, "Part"):
                contents = types.Content(parts=[types.Part(text=prompt)])
            else:
                contents = prompt
        except Exception:
            contents = prompt
        response = self.client.models.generate_content(
            model=CODE_GENERATION_MODEL,
            contents=contents,
        )
        text = (response.text or "").strip()
        if not text:
            raise ValueError("Empty response from code generation")
        if text.startswith("```python"):
            text = text[9:]
        if text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
        return text.strip()

    async def _write_code_background(self, coding_prompt: str, language: str) -> None:
        """Run code generation in a thread; when done, set last_code/code_status, print code, and notify the model so it can tell the user."""
        global last_code, code_status
        try:
            code = await asyncio.to_thread(
                self._generate_code_via_api_sync, coding_prompt
            )
            last_code = code
            code_status = True
            print("\n" + "=" * 60)
            print("WRITTEN CODE (Gemini API)")
            print("=" * 60)
            print(code)
            print("=" * 60 + "\n")
            # Notify the model so it can tell the user the code is ready
            if self.session and self.session_connected and hasattr(self.session, "send_client_content"):
                if Content is not None and Part is not None:
                    turn = Content(
                        role="user",
                        parts=[Part(text="[System: Code generation is complete. Tell the user: I've written the code. They can say 'execute' to run it on the robot.]")],
                    )
                    await self.session.send_client_content(turns=turn, turn_complete=True)
                else:
                    await self.session.send_client_content(
                        turns=[{"role": "user", "parts": [{"text": "[System: Code is ready. Tell the user they can say execute to run it.]"}]}],
                        turn_complete=True,
                    )
        except Exception as e:
            print(f"[DEBUG] writeCode background error: {e}")
            if self.session and self.session_connected and hasattr(self.session, "send_client_content"):
                try:
                    err_msg = f"[System: Code generation failed: {e}. Apologize to the user.]"
                    if Content is not None and Part is not None:
                        await self.session.send_client_content(
                            turns=Content(role="user", parts=[Part(text=err_msg)]),
                            turn_complete=True,
                        )
                    else:
                        await self.session.send_client_content(
                            turns=[{"role": "user", "parts": [{"text": err_msg}]}],
                            turn_complete=True,
                        )
                except Exception:
                    pass

    def _get_config(self):
        instructions = BASE_INSTRUCTIONS
        if self.user_name:
            instructions += f"\n\nThe user is {self.user_name}."
        if LiveConnectConfig is None:
            # Fallback dict config if google-genai types not available
            return {
                "response_modalities": ["AUDIO"],
                "system_instruction": instructions,
                "input_audio_transcription": {},
                "output_audio_transcription": {},
                "tools": [
                    {
                        "function_declarations": [{
                            "name": "retrieveMemory",
                            "description": "Retrieve past memories based on a natural language query. Do not use for identity questions (e.g. who am I, what is my name)—use the current speaker context instead.",
                            "parameters": {
                                "type": "OBJECT",
                                "properties": {"queryText": {"type": "STRING", "description": "Natural language query."}},
                                "required": ["queryText"],
                            },
                        }]
                    },
                    {
                        "function_declarations": [
                            {"name": "searchRobotActions", "description": "Search for available robot actions.", "parameters": {"type": "OBJECT", "properties": {"query": {"type": "STRING"}, "category": {"type": "STRING"}}, "required": ["query"]}},
                            {"name": "writeCode", "description": "Write or generate code for NAO V4 robot.", "parameters": {"type": "OBJECT", "properties": {"coding_prompt": {"type": "STRING"}, "prompt": {"type": "STRING"}, "language": {"type": "STRING"}}, "required": []}},
                            {"name": "executeCode", "description": "Send last_code to robot via TCP. Requires code_status True (call writeCode first).", "parameters": {"type": "OBJECT", "properties": {"code": {"type": "STRING"}, "language": {"type": "STRING"}}, "required": []}},
                            {"name": "saveCode", "description": "Save code to a file.", "parameters": {"type": "OBJECT", "properties": {"code": {"type": "STRING"}, "filename": {"type": "STRING"}}, "required": ["code", "filename"]}},
                            {"name": "updateMyName", "description": "Update the current speaker's name in the database. Call when the user says their name.", "parameters": {"type": "OBJECT", "properties": {"name": {"type": "STRING", "description": "The name the user wants to be called."}}, "required": ["name"]}},
                        ]
                    },
                ],
            }
        memory_tool = _get_retrieve_memory_tool()
        extra_tool = _get_extra_tools()
        tools = [t for t in [memory_tool, extra_tool] if t is not None]
        return LiveConnectConfig(
            output_audio_transcription={},
            input_audio_transcription={},
            response_modalities=["AUDIO"],
            speech_config=SpeechConfig(
                voice_config=VoiceConfig(
                    prebuilt_voice_config=PrebuiltVoiceConfig(voice_name=VOICE_NAME)
                )
            ),
            system_instruction=Content(parts=[Part(text=instructions)]),
            tools=tools,
        )

    async def retrieve_memory(self, query):
        """Retrieve memories from vector DB and knowledge graph."""
        print(f"\n🔍 [Retrieving] Query: '{query}'")
        results = []
        
        # Vector DB
        try:
            try:
                from .query import retrieve_and_rank
            except ImportError:
                from query import retrieve_and_rank
            
            print(f"[DEBUG] Querying vector DB: {query}")
            db_results = retrieve_and_rank(
                question=query, index_name="memobot-memories", top_k=5,
                alpha=0.5, beta=0.3, gamma=0.2, person_id=self.person_id,
            )
            for r in db_results:
                md = r.get("metadata", {})
                results.append({"source": "vector_db", "summary": md.get("summary", "")})
        except Exception as e:
            print(f"[DEBUG] Vector DB error: {e}")
        
        # Knowledge Graph
        if False and self.memobot_service and self.person_id: # Temporarily disabled
            try:
                print(f"[DEBUG] Querying KG with person_id: {self.person_id}")
                graph_response = await self.memobot_service.retrieve(query, person_id=self.person_id)
                if graph_response and isinstance(graph_response, dict):
                    for event in graph_response.get("events", []):
                        if isinstance(event, dict):
                            results.append({
                                "source": "knowledge_graph",
                                "summary": event.get("content", event.get("summary", "")),
                            })
            except Exception as e:
                print(f"[DEBUG] KG error: {e}")
        
        print(f"📋 Retrieved {len(results)} memories")
        for i, r in enumerate(results[:3], 1):
            print(f"  [{i}] Source: {r.get('source')} | {r.get('summary', 'N/A')[:500]}...")
        
        return {"events": results, "query": query}

    async def handle_tool_call(self, tool_call):
        """Handle function calls from Gemini."""
        global last_code, code_status, code_command_socket
        function_calls = getattr(tool_call, 'function_calls', []) or []
        function_responses = []
        
        for fc in function_calls:
            name = getattr(fc, 'name', None)
            call_id = getattr(fc, 'id', None)
            args = getattr(fc, 'args', {})
            
            if hasattr(args, 'items'):
                args = dict(args)
            
            print(f"[DEBUG] Function call: {name}, id={call_id}, args={args}")
            
            if name == "retrieveMemory":
                query_text = (args.get('queryText') or '').strip().lower()
                result = await self.retrieve_memory(query_text)
                func_response = types.FunctionResponse(
                    id=call_id,
                    name=name,
                    response={"result": result},
                )
                function_responses.append(func_response)
            elif name == "searchRobotActions":
                query = args.get("query", "")
                category = args.get("category", "")
                # Placeholder result
                result = {
                    "actions": [
                        {"id": "move_forward", "name": "Move Forward", "category": "movement", "description": "[placeholder] Move robot forward."},
                        {"id": "grasp", "name": "Grasp", "category": "manipulation", "description": "[placeholder] Grasp object."},
                        {"id": "speak", "name": "Speak", "category": "speech", "description": "[placeholder] Speak text."},
                    ],
                    "query": query,
                    "category": category or None,
                }
                function_responses.append(types.FunctionResponse(id=call_id, name=name, response={"result": result}))
            elif name == "writeCode":
                coding_prompt = args.get("coding_prompt") or args.get("prompt", "")
                language = args.get("language", "python")
                if coding_prompt:
                    # Nonblocking: return immediately so the model can say "I'm writing the code"
                    result = {
                        "status": "pending",
                        "code": None,
                        "language": language,
                        "coding_prompt": coding_prompt,
                        "message": "You are now generating the code. Tell the user you're writing it and will tell them when it's ready.",
                    }
                    function_responses.append(
                        types.FunctionResponse(id=call_id, name=name, response={"result": result})
                    )
                    # Run generation in background; when done, update state and notify model
                    asyncio.create_task(
                        self._write_code_background(coding_prompt, language)
                    )
                else:
                    result = {
                        "code": None,
                        "language": language,
                        "coding_prompt": coding_prompt,
                        "message": "No coding_prompt provided.",
                    }
                    function_responses.append(
                        types.FunctionResponse(id=call_id, name=name, response={"result": result})
                    )
            elif name == "executeCode":
                if not code_status:
                    result = {
                        "executed": False,
                        "message": "The code is not ready yet. Generate code first using the writeCode tool, then ask to execute.",
                    }
                    function_responses.append(types.FunctionResponse(id=call_id, name=name, response={"result": result}))
                else:
                    # Send last_code to robot client via TCP (length-prefixed, same as vibe_test_server)
                    sent = False
                    err = None
                    if code_command_socket and last_code:
                        try:
                            payload = last_code.encode("utf-8")
                            header = struct.pack(">L", len(payload))
                            code_command_socket.sendall(header + payload)
                            sent = True
                            print("[DEBUG] executeCode: last_code sent to robot client.")
                        except Exception as e:
                            err = str(e)
                            print(f"[DEBUG] executeCode send error: {e}")
                    result = {
                        "executed": sent,
                        "message": "Code sent to robot." if sent else (err or "No robot client connected to receive code."),
                        "code_length": len(last_code) if last_code else 0,
                    }
                    function_responses.append(types.FunctionResponse(id=call_id, name=name, response={"result": result}))
            elif name == "saveCode":
                code = args.get("code", "")
                filename = args.get("filename", "")
                # Placeholder result
                result = {
                    "saved": True,
                    "filename": filename,
                    "message": "[placeholder] Code saved successfully",
                    "bytes_written": len(code.encode("utf-8")),
                }
                function_responses.append(types.FunctionResponse(id=call_id, name=name, response={"result": result}))
            elif name == "updateMyName":
                new_name = (args.get("name") or "").strip()
                if not new_name:
                    result = {"updated": False, "message": "No name provided."}
                elif not self.person_id:
                    result = {"updated": False, "message": "No current speaker identified. Name can only be updated for a recognized speaker."}
                else:
                    try:
                        try:
                            from memobot.utils.database import update_person_name_by_person_id
                        except ImportError:
                            from utils.database import update_person_name_by_person_id
                        updated = update_person_name_by_person_id(self.person_id, new_name)
                        if updated:
                            self.user_name = new_name
                            result = {"updated": True, "name": new_name, "message": f"Name updated to {new_name} in the database."}
                            print(f"[Database] updateMyName: person_id={self.person_id!r} -> name={new_name!r}")
                        else:
                            result = {"updated": False, "message": "No matching person found in the database."}
                    except Exception as e:
                        result = {"updated": False, "message": f"Database error: {e}"}
                        print(f"[DEBUG] updateMyName error: {e}")
                function_responses.append(types.FunctionResponse(id=call_id, name=name, response={"result": result}))
        
        # Send all function responses at once
        if function_responses:
            try:
                # Wrap responses in LiveClientToolResponse and use generic send()
                tool_response = types.LiveClientToolResponse(function_responses=function_responses)
                await self.session.send(input=tool_response)
                print(f"[DEBUG] Tool response sent successfully")
            except Exception as e:
                print(f"[DEBUG] Tool response error: {e}")

    async def listen_audio(self):
        """Capture audio from microphone and queue it."""
        try:
            while self.audio_mgr.is_running:
                data = await asyncio.to_thread(self.audio_mgr.read_mic)
                try:
                    self.audio_queue_mic.put_nowait({"data": data, "mime_type": "audio/pcm"})
                except asyncio.QueueFull:
                    # Drop oldest frame if queue is full to maintain real-time behavior
                    try:
                        self.audio_queue_mic.get_nowait()
                        self.audio_queue_mic.put_nowait({"data": data, "mime_type": "audio/pcm"})
                    except:
                        pass
                # Sleep for chunk duration to maintain timing
                await asyncio.sleep(CHUNK_SIZE / SEND_SAMPLE_RATE)
        except asyncio.CancelledError:
            print("[DEBUG] listen_audio cancelled")
            raise

    async def send_audio(self):
        """Send queued audio to Gemini."""
        try:
            while True:
                msg = await self.audio_queue_mic.get()
                # Use send() with the audio data directly
                await self.session.send(input=msg)
        except asyncio.CancelledError:
            print("[DEBUG] send_audio cancelled")
            raise

    async def receive_responses(self):
        """Receive responses from Gemini (matches working Live API receive pattern)."""
        try:
            while True:
                turn = self.session.receive()
                ai_text_started = False  # Print "Gemini said:" prefix once per turn
                async for response in turn:
                    # Audio: use response.data (aggregated inline_data) when present
                    if response.data:
                        self.audio_mgr.queue_audio(response.data)
                    # Text: print what the AI says (with prefix once per turn)
                    if response.text:
                        if not ai_text_started:
                            print("\n🗣️ Gemini said: ", end="")
                            ai_text_started = True
                        print(response.text, end="")

                    server_content = response.server_content
                    if server_content:
                        # Print user speech (transcription; API returns object with .text when input_audio_transcription enabled)
                        if getattr(server_content, "input_transcription", None):
                            it = server_content.input_transcription
                            text = it.get("text", it) if isinstance(it, dict) else getattr(it, "text", it)
                            if text:
                                print(f"\n👤 You said: {text}")
                        # Print AI speech transcript when available
                        if getattr(server_content, "output_transcription", None):
                            ot = server_content.output_transcription
                            text = ot.get("text", ot) if isinstance(ot, dict) else getattr(ot, "text", ot)
                            if text:
                                if not ai_text_started:
                                    print("\n🗣️ Gemini said: ", end="")
                                    ai_text_started = True
                                print(text, end="")
                        # Only print "Audio playback interrupted" when user talked over AI, not when AI finished
                        if server_content.interrupted:
                            self.audio_mgr.interrupt(print_message=True)
                        elif server_content.turn_complete:
                            if ai_text_started:
                                print()  # Newline after AI response
                            self.audio_mgr.interrupt(print_message=False)

                    if response.tool_call:
                        print("\n[DEBUG] Tool call received")
                        await self.handle_tool_call(response.tool_call)

                # After turn ends: clear queue so playback stops (no message—AI just finished)
                self.audio_mgr.interrupt(print_message=False)
        except asyncio.CancelledError:
            print("[DEBUG] receive_responses cancelled")
            raise
        except Exception as e:
            print(f"[ERROR] receive_responses error: {e}")
            import traceback
            traceback.print_exc()

    async def run(self):
        """Main run loop."""
        print("🎙️  Initializing Audio Manager...")
        await self.audio_mgr.init()
        
        config = self._get_config()
        _patch_live_setup_for_transcription()
        _patch_live_parse_transcription()

        try:
            async with self.client.aio.live.connect(model=MODEL, config=config) as session:
                self.session = session
                print("✅ Connected to Gemini Live API!")
                print("🎙️  Start speaking...\n")
                
                # Create tasks manually for better control
                tasks = [
                    asyncio.create_task(self.listen_audio(), name="listen"),
                    asyncio.create_task(self.send_audio(), name="send"),
                    asyncio.create_task(self.receive_responses(), name="receive"),
                ]
                
                try:
                    # Wait for any task to complete (which would indicate an error)
                    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
                    
                    # Check if any task raised an exception
                    for task in done:
                        if task.exception():
                            print(f"[ERROR] Task {task.get_name()} failed: {task.exception()}")
                finally:
                    # Cancel all remaining tasks
                    for task in tasks:
                        if not task.done():
                            task.cancel()
                    
                    # Wait for all tasks to finish cancellation
                    await asyncio.gather(*tasks, return_exceptions=True)
                    
        except asyncio.CancelledError:
            pass
        except Exception as e:
            print(f"[ERROR] Run error: {e}")
            import traceback
            traceback.print_exc()
        finally:
            await self.cleanup()

    async def cleanup(self):
        """Clean up resources."""
        self.audio_mgr.cleanup()
        if self.memobot_service:
            try:
                await self.memobot_service.close()
            except:
                pass
        print("\n👋 Connection closed.")


def _resample_audio(audio_bytes: bytes, src_rate: int, dst_rate: int) -> bytes:
    """Resample audio bytes from src_rate to dst_rate (16-bit mono PCM)."""
    if src_rate == dst_rate or np is None:
        return audio_bytes
    audio_data = np.frombuffer(audio_bytes, dtype=np.int16)
    src_len = len(audio_data)
    dst_len = int(src_len * dst_rate / src_rate)
    src_x = np.linspace(0, src_len, src_len)
    dst_x = np.linspace(0, src_len, dst_len)
    resampled = np.interp(dst_x, src_x, audio_data).astype(np.int16)
    return resampled.tobytes()


# Robot server: TTS playback padding for is_robot_speaking()
PLAYBACK_PADDING = 0.5
ROBOT_SAMPLE_RATE = 16000


class ServerRealtimeAgent(RealtimeAgent):
    """
    Gemini Live agent for robot server: audio comes from robot mic (ingest_robot_audio),
    TTS is pushed to a queue for the robot to play. No local mic/speaker.
    """

    def __init__(self, api_key=None, user_name=None, person_id=None, audio_tx_queue=None, loop=None):
        super().__init__(api_key=api_key, user_name=user_name, person_id=person_id)
        self.audio_tx_queue = audio_tx_queue if audio_tx_queue is not None else queue.Queue()
        self.loop = loop
        self.session_connected = False
        self.playback_end_time = 0.0
        self.state_lock = threading.Lock()
        self._pending_identity_confirmation = False

    def is_robot_speaking(self):
        with self.state_lock:
            return time.time() < (self.playback_end_time + PLAYBACK_PADDING)

    def _register_audio_payload(self, audio_bytes_16k: bytes):
        duration = len(audio_bytes_16k) / (ROBOT_SAMPLE_RATE * 2)
        current = time.time()
        with self.state_lock:
            if self.playback_end_time > current:
                self.playback_end_time += duration
            else:
                self.playback_end_time = current + duration

    def ingest_robot_audio(self, audio_bytes_16k: bytes):
        """Push robot mic audio into the send queue so send_audio sends it to Gemini. Thread-safe."""
        msg = {"data": audio_bytes_16k, "mime_type": "audio/pcm"}
        if self.loop and self.audio_queue_mic is not None:
            def _put():
                try:
                    self.audio_queue_mic.put_nowait(msg)
                except asyncio.QueueFull:
                    try:
                        self.audio_queue_mic.get_nowait()
                        self.audio_queue_mic.put_nowait(msg)
                    except Exception:
                        pass
            try:
                self.loop.call_soon_threadsafe(_put)
            except Exception:
                pass

    async def update_speaker_identity(self, user_name, person_id=None, is_new_user=False):
        """
        Update current speaker.
        CRITICAL: We send with turn_complete=True so the model processes this immediately
        and commits it to conversation history (required for "who am I?" to work).
        """
        self.user_name = user_name
        self.person_id = person_id
        if not self.session or not self.session_connected:
            print(f"[Live API] update_speaker_identity skipped: no session or not connected (user_name={user_name!r})")
            return

        display_name = user_name if user_name else "Guest"
        text = (
            f"[SYSTEM EVENT: User changed. You are now talking to {display_name}. The active speaker is now {display_name}. Don't say anything."
        )

        try:
            print(f"[Live API] Updating identity to '{display_name}' (turn_complete=True)...")
            self._pending_identity_confirmation = True
            if hasattr(self.session, "send_client_content"):
                if Content is not None and Part is not None:
                    turn_content = Content(role="user", parts=[Part(text=text)])
                    await self.session.send_client_content(turns=turn_content, turn_complete=True)
                else:
                    await self.session.send_client_content(
                        turns=[{"role": "user", "parts": [{"text": text}]}],
                        turn_complete=True,
                    )
            else:
                await self.session.send(input=text, end_of_turn=True)
        except Exception as e:
            print(f"Error updating identity: {e}")
            self._pending_identity_confirmation = False

    async def run(self):
        """Run Gemini Live session: no local audio init; feed mic via ingest_robot_audio; TTS -> audio_tx_queue."""
        config = self._get_config()
        _patch_live_setup_for_transcription()
        _patch_live_parse_transcription()

        try:
            async with self.client.aio.live.connect(model=MODEL, config=config) as session:
                self.session = session
                self.session_connected = True
                print("✅ Connected to Gemini Live API (robot server mode)!")
                print("🎙️  Robot mic will be sent to Gemini; TTS will play on robot.\n")

                async def send_audio():
                    try:
                        while True:
                            try:
                                msg = await self.audio_queue_mic.get()
                                await self.session.send(input=msg)
                            except asyncio.CancelledError:
                                raise
                            except Exception as e:
                                if WsConnectionClosedError is not None and isinstance(e, WsConnectionClosedError):
                                    print(f"[WARN] send_audio: connection closed (1008 policy), continuing: {e}")
                                    continue
                                if "1008" in str(e) or "policy violation" in str(e).lower():
                                    print(f"[WARN] send_audio: policy violation / connection closed, continuing: {e}")
                                    continue
                                print(f"[ERROR] send_audio: {e}")
                                continue
                    except asyncio.CancelledError:
                        raise

                async def receive_responses():
                    try:
                        while True:
                            try:
                                turn = self.session.receive()
                                ai_text_started = False
                                silence_this_turn = False  # Set when identity confirmation (short reply) so we don't speak it
                                async for response in turn:
                                    if response.data:
                                        if not silence_this_turn:
                                            # Gemini outputs 24kHz; robot expects 16kHz
                                            audio_16k = _resample_audio(
                                                response.data, RECEIVE_SAMPLE_RATE, ROBOT_SAMPLE_RATE
                                            )
                                            self._register_audio_payload(audio_16k)
                                            if self.audio_tx_queue is not None:
                                                self.audio_tx_queue.put(audio_16k)
                                    if response.text:
                                        # If this is the short "Hello X" identity confirmation, don't speak it
                                        if getattr(self, "_pending_identity_confirmation", False) and len((response.text or "").strip()) < 50:
                                            silence_this_turn = True
                                            print(f"\n🤫 (Silenced identity confirmation): {response.text.strip()!r}")
                                            self._pending_identity_confirmation = False
                                        elif not silence_this_turn:
                                            if not ai_text_started:
                                                print("\n🗣️ Gemini said: ", end="")
                                                ai_text_started = True
                                            print(response.text, end="")
                                    server_content = response.server_content
                                    if server_content:
                                        if getattr(server_content, "input_transcription", None):
                                            it = server_content.input_transcription
                                            text = it.get("text", it) if isinstance(it, dict) else getattr(it, "text", it)
                                            if text:
                                                print(f"\n👤 You said: {text}")
                                        if getattr(server_content, "output_transcription", None):
                                            ot = server_content.output_transcription
                                            text = ot.get("text", ot) if isinstance(ot, dict) else getattr(ot, "text", ot)
                                            if text and not ai_text_started:
                                                print("\n🗣️ Gemini said: ", end="")
                                                ai_text_started = True
                                            if text:
                                                print(text, end="")
                                        if server_content.interrupted or server_content.turn_complete:
                                            if ai_text_started:
                                                print()
                                    if response.tool_call:
                                        await self.handle_tool_call(response.tool_call)
                                # Turn ended
                                if getattr(self, "_pending_identity_confirmation", False) and not silence_this_turn:
                                    self._pending_identity_confirmation = False
                                if ai_text_started:
                                    print()
                            except asyncio.CancelledError:
                                raise
                            except Exception as e:
                                if WsConnectionClosedError is not None and isinstance(e, WsConnectionClosedError):
                                    print(f"[WARN] receive_responses: connection closed (1008 policy), continuing: {e}")
                                    continue
                                if "1008" in str(e) or "policy violation" in str(e).lower():
                                    print(f"[WARN] receive_responses: policy violation / connection closed, continuing: {e}")
                                    continue
                                print(f"[ERROR] receive_responses: {e}")
                                import traceback
                                traceback.print_exc()
                                continue
                    except asyncio.CancelledError:
                        raise
                    except Exception as e:
                        print(f"[ERROR] receive_responses: {e}")
                        import traceback
                        traceback.print_exc()

                tasks = [
                    asyncio.create_task(send_audio(), name="send"),
                    asyncio.create_task(receive_responses(), name="receive"),
                ]
                try:
                    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
                    for task in done:
                        if task.exception():
                            print(f"[ERROR] Task {task.get_name()} failed: {task.exception()}")
                finally:
                    for task in tasks:
                        if not task.done():
                            task.cancel()
                    await asyncio.gather(*tasks, return_exceptions=True)
        except asyncio.CancelledError:
            pass
        except Exception as e:
            print(f"[ERROR] ServerRealtimeAgent run: {e}")
            import traceback
            traceback.print_exc()
        finally:
            self.session_connected = False
            if self.memobot_service:
                try:
                    await self.memobot_service.close()
                except Exception:
                    pass
            print("\n👋 Gemini Live (robot server) connection closed.")

    async def cleanup(self):
        """No local audio to clean up."""
        if self.memobot_service:
            try:
                await self.memobot_service.close()
            except Exception:
                pass


def _patch_live_setup_for_transcription():
    """Patch SDK so setup message includes input/output_audio_transcription (API requires it for transcriptions)."""
    try:
        from google.genai import live as live_module
        _orig_mldev = live_module.AsyncLive._LiveSetup_to_mldev

        def _patched_mldev(self, model, config=None):
            result = _orig_mldev(self, model, config)
            from_object = config.model_dump(exclude_none=True) if isinstance(config, types.LiveConnectConfig) else (config or {})
            if "setup" not in result:
                return result
            # Always request transcriptions so API returns "You said" / "Gemini said" (SDK may drop these from config)
            result["setup"]["inputAudioTranscription"] = from_object.get("input_audio_transcription", {})
            result["setup"]["outputAudioTranscription"] = from_object.get("output_audio_transcription", {})
            return result

        live_module.AsyncLive._LiveSetup_to_mldev = _patched_mldev
    except Exception:
        pass


def _patch_live_parse_transcription():
    """Patch SDK to pass through inputTranscription/outputTranscription from API into server_content."""
    try:
        from typing import Any, Optional
        from google.genai import live as live_module
        from google.genai import types as genai_types
        _orig_content_from_mldev = live_module.AsyncLive._LiveServerContent_from_mldev

        def _patched_content_from_mldev(self, from_object):
            to_object = _orig_content_from_mldev(self, from_object)
            sc = from_object if isinstance(from_object, dict) else getattr(from_object, "__dict__", {})
            if sc.get("inputTranscription") is not None:
                setattr(to_object, "input_transcription", sc["inputTranscription"])
            if sc.get("outputTranscription") is not None:
                setattr(to_object, "output_transcription", sc["outputTranscription"])
            return to_object

        live_module.AsyncLive._LiveServerContent_from_mldev = _patched_content_from_mldev

        # Subclass so parsed messages have .input_transcription / .output_transcription (SDK model ignores extra)
        _base = genai_types.LiveServerContent
        if not hasattr(_base, "input_transcription"):
            class _LiveServerContentWithTranscription(_base):
                input_transcription: Optional[Any] = None
                output_transcription: Optional[Any] = None
            genai_types.LiveServerContent = _LiveServerContentWithTranscription
    except Exception:
        pass


def run_realtime_mode(user_name=None, person_id=None):
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print("\nERROR: GOOGLE_API_KEY is not set.")
        sys.exit(1)
    
    if not pyaudio:
        print("\nERROR: pyaudio is required. Install with: pip install pyaudio")
        sys.exit(1)
    
    print("\n🎙️  Memobot Realtime Audio Mode (Gemini)")
    print("=" * 40)
    if user_name:
        print(f"User: {user_name}")
    if person_id:
        print(f"Person ID: {person_id}")
    print("=" * 40)
    
    agent = RealtimeAgent(api_key, user_name=user_name, person_id=person_id)
    
    try:
        asyncio.run(agent.run())
    except KeyboardInterrupt:
        print("\nInterrupted by user.")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Memobot - AI assistant with memory")
    parser.add_argument("--user-name", default=None)
    parser.add_argument("--person-id", default=None)
    args = parser.parse_args()
    run_realtime_mode(user_name=args.user_name, person_id=args.person_id)